//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoDepotFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coin
    {
        public string ticker { get; set; }
        public string btc { get; set; }
        public string name { get; set; }
        public string rank { get; set; }
        public string usd { get; set; }
        public Nullable<double> stdv { get; set; }
    }
}
