//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoDepotFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crptodepot
    {
        public int ID { get; set; }
        public string Currency_Name { get; set; }
        public decimal Value { get; set; }
        public Nullable<decimal> Trend__Today_ { get; set; }
        public Nullable<decimal> Trend__This_Week_ { get; set; }
        public Nullable<decimal> Trend__This_month_ { get; set; }
        public Nullable<System.DateTime> Date_tracked { get; set; }
    }
}
